version: '3.3'  

services:
  todo-frontend:
    image: hello-front-prod
    build:
      context: .
      dockerfile: ./todo-frontend/Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 3001:3000
    container_name: pro-todo-frontend
    
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6378:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

  todo-backend:
    image: backend-prod
    build:
      context: .
      dockerfile: ./todo-backend/Dockerfile
    ports:
      - 3002:3000
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: pro-todo-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: pro-todo-reverse-proxy
    depends_on:
      - todo-frontend # wait for the frontend container to be started
      - todo-backend


volumes:
  mongo_data:
  redis_data:
    
 